name: Upload Historical Releases
on: 
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for ver in "0.1.0" "0.1.1" "0.1.2" "0.2.0" "0.3.0" "0.3.1" "0.3.2" "0.3.3"; do
            echo "Publishing v$ver"
            gh release create "v$ver" website/downloads/KeyR_v${ver}_win_x64.exe --title "KeyR v$ver Beta" --notes "Historical Beta Release" --prerelease || true
          done
